"""empty message

Revision ID: 379603fc67bf
Revises: f3eb32233f87
Create Date: 2023-06-01 15:37:13.316582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379603fc67bf'
down_revision = 'f3eb32233f87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
