"""empty message

Revision ID: 37a380561b7a
Revises: 924a4546f0ac
Create Date: 2023-06-02 13:53:30.120585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a380561b7a'
down_revision = '924a4546f0ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
