"""empty message

Revision ID: 48506f4bf169
Revises: 952838cc4c49
Create Date: 2023-06-05 16:50:49.020014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48506f4bf169'
down_revision = '952838cc4c49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
