"""empty message

Revision ID: 924a4546f0ac
Revises: 379603fc67bf
Create Date: 2023-06-01 15:37:49.702385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924a4546f0ac'
down_revision = '379603fc67bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_item_category_id_category')),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_item_creator_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item')),
    sa.UniqueConstraint('name', name=op.f('uq_item_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
