"""empty message

Revision ID: 952838cc4c49
Revises: 37a380561b7a
Create Date: 2023-06-02 14:03:25.253561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952838cc4c49'
down_revision = '37a380561b7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
