"""empty message

Revision ID: c7e3d084c0c4
Revises: 48506f4bf169
Create Date: 2023-06-05 17:20:05.518469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e3d084c0c4'
down_revision = '48506f4bf169'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
